apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go-web-app
spec:
  ingressClassName: nginx
  rules:
  - host: "go.demo-application"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-web-app
            port:
              number: 80